---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-ses-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ses.services.k8s.aws
  resources:
  - customverificationemailtemplates
  - receiptrulesets
  verbs:
  - get
  - list
  - watch
