---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-ses-reader
  namespace: default
rules:
- apiGroups:
  - ses.services.k8s.aws
  resources:
  - configurationsets
  - configurationseteventdestinations
  - customverificationemailtemplates
  - receiptfilters
  - receiptrules
  - receiptrulesets
  - templates
  verbs:
  - get
  - list
  - watch
