// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package configuration_set_event_destination

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"
	snsapitypes "github.com/aws-controllers-k8s/sns-controller/apis/v1alpha1"

	svcapitypes "github.com/aws-controllers-k8s/ses-controller/apis/v1alpha1"
)

// +kubebuilder:rbac:groups=sns.services.k8s.aws,resources=topics,verbs=get;list
// +kubebuilder:rbac:groups=sns.services.k8s.aws,resources=topics/status,verbs=get;list

// ClearResolvedReferences removes any reference values that were made
// concrete in the spec. It returns a copy of the input AWSResource which
// contains the original *Ref values, but none of their respective concrete
// values.
func (rm *resourceManager) ClearResolvedReferences(res acktypes.AWSResource) acktypes.AWSResource {
	ko := rm.concreteResource(res).ko.DeepCopy()

	if ko.Spec.ConfigurationSetRef != nil {
		ko.Spec.ConfigurationSetName = nil
	}

	if ko.Spec.EventDestination != nil {
		if ko.Spec.EventDestination.SNSDestination != nil {
			if ko.Spec.EventDestination.SNSDestination.TopicRef != nil {
				ko.Spec.EventDestination.SNSDestination.TopicARN = nil
			}
		}
	}

	return &resource{ko}
}

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve those
// reference field(s) into their respective target field(s). It returns a
// copy of the input AWSResource with resolved reference(s), a boolean which
// is set to true if the resource contains any references (regardless of if
// they are resolved successfully) and an error if the passed AWSResource's
// reference field(s) could not be resolved.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, bool, error) {
	ko := rm.concreteResource(res).ko

	resourceHasReferences := false
	err := validateReferenceFields(ko)
	if fieldHasReferences, err := rm.resolveReferenceForConfigurationSetName(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	if fieldHasReferences, err := rm.resolveReferenceForEventDestination_SNSDestination_TopicARN(ctx, apiReader, ko); err != nil {
		return &resource{ko}, (resourceHasReferences || fieldHasReferences), err
	} else {
		resourceHasReferences = resourceHasReferences || fieldHasReferences
	}

	return &resource{ko}, resourceHasReferences, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.ConfigurationSetEventDestination) error {

	if ko.Spec.ConfigurationSetRef != nil && ko.Spec.ConfigurationSetName != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("ConfigurationSetName", "ConfigurationSetRef")
	}
	if ko.Spec.ConfigurationSetRef == nil && ko.Spec.ConfigurationSetName == nil {
		return ackerr.ResourceReferenceOrIDRequiredFor("ConfigurationSetName", "ConfigurationSetRef")
	}

	if ko.Spec.EventDestination != nil {
		if ko.Spec.EventDestination.SNSDestination != nil {
			if ko.Spec.EventDestination.SNSDestination.TopicRef != nil && ko.Spec.EventDestination.SNSDestination.TopicARN != nil {
				return ackerr.ResourceReferenceAndIDNotSupportedFor("EventDestination.SNSDestination.TopicARN", "EventDestination.SNSDestination.TopicRef")
			}
			if ko.Spec.EventDestination.SNSDestination.TopicRef == nil && ko.Spec.EventDestination.SNSDestination.TopicARN == nil {
				return ackerr.ResourceReferenceOrIDRequiredFor("TopicARN", "TopicRef")
			}
		}
	}
	return nil
}

// resolveReferenceForConfigurationSetName reads the resource referenced
// from ConfigurationSetRef field and sets the ConfigurationSetName
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForConfigurationSetName(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.ConfigurationSetEventDestination,
) (hasReferences bool, err error) {
	if ko.Spec.ConfigurationSetRef != nil && ko.Spec.ConfigurationSetRef.From != nil {
		hasReferences = true
		arr := ko.Spec.ConfigurationSetRef.From
		if arr.Name == nil || *arr.Name == "" {
			return hasReferences, fmt.Errorf("provided resource reference is nil or empty: ConfigurationSetRef")
		}
		namespace := ko.ObjectMeta.GetNamespace()
		if arr.Namespace != nil && *arr.Namespace != "" {
			namespace = *arr.Namespace
		}
		obj := &svcapitypes.ConfigurationSet{}
		if err := getReferencedResourceState_ConfigurationSet(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
			return hasReferences, err
		}
		ko.Spec.ConfigurationSetName = (*string)(obj.Spec.Name)
	}

	return hasReferences, nil
}

// getReferencedResourceState_ConfigurationSet looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_ConfigurationSet(
	ctx context.Context,
	apiReader client.Reader,
	obj *svcapitypes.ConfigurationSet,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"ConfigurationSet",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"ConfigurationSet",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"ConfigurationSet",
			namespace, name)
	}
	if obj.Spec.Name == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"ConfigurationSet",
			namespace, name,
			"Spec.Name")
	}
	return nil
}

// resolveReferenceForEventDestination_SNSDestination_TopicARN reads the resource referenced
// from EventDestination.SNSDestination.TopicRef field and sets the EventDestination.SNSDestination.TopicARN
// from referenced resource. Returns a boolean indicating whether a reference
// contains references, or an error
func (rm *resourceManager) resolveReferenceForEventDestination_SNSDestination_TopicARN(
	ctx context.Context,
	apiReader client.Reader,
	ko *svcapitypes.ConfigurationSetEventDestination,
) (hasReferences bool, err error) {
	if ko.Spec.EventDestination != nil {
		if ko.Spec.EventDestination.SNSDestination != nil {
			if ko.Spec.EventDestination.SNSDestination.TopicRef != nil && ko.Spec.EventDestination.SNSDestination.TopicRef.From != nil {
				hasReferences = true
				arr := ko.Spec.EventDestination.SNSDestination.TopicRef.From
				if arr.Name == nil || *arr.Name == "" {
					return hasReferences, fmt.Errorf("provided resource reference is nil or empty: EventDestination.SNSDestination.TopicRef")
				}
				namespace := ko.ObjectMeta.GetNamespace()
				if arr.Namespace != nil && *arr.Namespace != "" {
					namespace = *arr.Namespace
				}
				obj := &snsapitypes.Topic{}
				if err := getReferencedResourceState_Topic(ctx, apiReader, obj, *arr.Name, namespace); err != nil {
					return hasReferences, err
				}
				ko.Spec.EventDestination.SNSDestination.TopicARN = (*string)(obj.Status.TopicARN)
			}
		}
	}

	return hasReferences, nil
}

// getReferencedResourceState_Topic looks up whether a referenced resource
// exists and is in a ACK.ResourceSynced=True state. If the referenced resource does exist and is
// in a Synced state, returns nil, otherwise returns `ackerr.ResourceReferenceTerminalFor` or
// `ResourceReferenceNotSyncedFor` depending on if the resource is in a Terminal state.
func getReferencedResourceState_Topic(
	ctx context.Context,
	apiReader client.Reader,
	obj *snsapitypes.Topic,
	name string, // the Kubernetes name of the referenced resource
	namespace string, // the Kubernetes namespace of the referenced resource
) error {
	namespacedName := types.NamespacedName{
		Namespace: namespace,
		Name:      name,
	}
	err := apiReader.Get(ctx, namespacedName, obj)
	if err != nil {
		return err
	}
	var refResourceTerminal bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
			cond.Status == corev1.ConditionTrue {
			return ackerr.ResourceReferenceTerminalFor(
				"Topic",
				namespace, name)
		}
	}
	if refResourceTerminal {
		return ackerr.ResourceReferenceTerminalFor(
			"Topic",
			namespace, name)
	}
	var refResourceSynced bool
	for _, cond := range obj.Status.Conditions {
		if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
			cond.Status == corev1.ConditionTrue {
			refResourceSynced = true
		}
	}
	if !refResourceSynced {
		return ackerr.ResourceReferenceNotSyncedFor(
			"Topic",
			namespace, name)
	}
	if obj.Status.TopicARN == nil {
		return ackerr.ResourceReferenceMissingTargetFieldFor(
			"Topic",
			namespace, name,
			"Status.TopicARN")
	}
	return nil
}
