// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package custom_verification_email_template

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.FailureRedirectionURL, b.ko.Spec.FailureRedirectionURL) {
		delta.Add("Spec.FailureRedirectionURL", a.ko.Spec.FailureRedirectionURL, b.ko.Spec.FailureRedirectionURL)
	} else if a.ko.Spec.FailureRedirectionURL != nil && b.ko.Spec.FailureRedirectionURL != nil {
		if *a.ko.Spec.FailureRedirectionURL != *b.ko.Spec.FailureRedirectionURL {
			delta.Add("Spec.FailureRedirectionURL", a.ko.Spec.FailureRedirectionURL, b.ko.Spec.FailureRedirectionURL)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.FromEmailAddress, b.ko.Spec.FromEmailAddress) {
		delta.Add("Spec.FromEmailAddress", a.ko.Spec.FromEmailAddress, b.ko.Spec.FromEmailAddress)
	} else if a.ko.Spec.FromEmailAddress != nil && b.ko.Spec.FromEmailAddress != nil {
		if *a.ko.Spec.FromEmailAddress != *b.ko.Spec.FromEmailAddress {
			delta.Add("Spec.FromEmailAddress", a.ko.Spec.FromEmailAddress, b.ko.Spec.FromEmailAddress)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.SuccessRedirectionURL, b.ko.Spec.SuccessRedirectionURL) {
		delta.Add("Spec.SuccessRedirectionURL", a.ko.Spec.SuccessRedirectionURL, b.ko.Spec.SuccessRedirectionURL)
	} else if a.ko.Spec.SuccessRedirectionURL != nil && b.ko.Spec.SuccessRedirectionURL != nil {
		if *a.ko.Spec.SuccessRedirectionURL != *b.ko.Spec.SuccessRedirectionURL {
			delta.Add("Spec.SuccessRedirectionURL", a.ko.Spec.SuccessRedirectionURL, b.ko.Spec.SuccessRedirectionURL)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TemplateContent, b.ko.Spec.TemplateContent) {
		delta.Add("Spec.TemplateContent", a.ko.Spec.TemplateContent, b.ko.Spec.TemplateContent)
	} else if a.ko.Spec.TemplateContent != nil && b.ko.Spec.TemplateContent != nil {
		if *a.ko.Spec.TemplateContent != *b.ko.Spec.TemplateContent {
			delta.Add("Spec.TemplateContent", a.ko.Spec.TemplateContent, b.ko.Spec.TemplateContent)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TemplateName, b.ko.Spec.TemplateName) {
		delta.Add("Spec.TemplateName", a.ko.Spec.TemplateName, b.ko.Spec.TemplateName)
	} else if a.ko.Spec.TemplateName != nil && b.ko.Spec.TemplateName != nil {
		if *a.ko.Spec.TemplateName != *b.ko.Spec.TemplateName {
			delta.Add("Spec.TemplateName", a.ko.Spec.TemplateName, b.ko.Spec.TemplateName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.TemplateSubject, b.ko.Spec.TemplateSubject) {
		delta.Add("Spec.TemplateSubject", a.ko.Spec.TemplateSubject, b.ko.Spec.TemplateSubject)
	} else if a.ko.Spec.TemplateSubject != nil && b.ko.Spec.TemplateSubject != nil {
		if *a.ko.Spec.TemplateSubject != *b.ko.Spec.TemplateSubject {
			delta.Add("Spec.TemplateSubject", a.ko.Spec.TemplateSubject, b.ko.Spec.TemplateSubject)
		}
	}

	return delta
}
