// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConfigurationSetEventDestinationSpec defines the desired state of ConfigurationSetEventDestination.
type ConfigurationSetEventDestinationSpec struct {

	// The name of the configuration set that the event destination should be associated
	// with.
	// +kubebuilder:validation:Required
	ConfigurationSetName *string `json:"configurationSetName"`
	// An object that describes the Amazon Web Services service that email sending
	// event where information is published.
	// +kubebuilder:validation:Required
	EventDestination *EventDestination `json:"eventDestination"`
}

// ConfigurationSetEventDestinationStatus defines the observed state of ConfigurationSetEventDestination
type ConfigurationSetEventDestinationStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// ConfigurationSetEventDestination is the Schema for the ConfigurationSetEventDestinations API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ConfigurationSetEventDestination struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ConfigurationSetEventDestinationSpec   `json:"spec,omitempty"`
	Status            ConfigurationSetEventDestinationStatus `json:"status,omitempty"`
}

// ConfigurationSetEventDestinationList contains a list of ConfigurationSetEventDestination
// +kubebuilder:object:root=true
type ConfigurationSetEventDestinationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ConfigurationSetEventDestination `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ConfigurationSetEventDestination{}, &ConfigurationSetEventDestinationList{})
}
