// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ReceiptRuleSetSpec defines the desired state of ReceiptRuleSet.
type ReceiptRuleSetSpec struct {

	// The name of the rule set to create. The name must meet the following requirements:
	//
	//   - Contain only ASCII letters (a-z, A-Z), numbers (0-9), underscores (_),
	//     or dashes (-).
	//
	//   - Start and end with a letter or number.
	//
	//   - Contain 64 characters or fewer.
	//
	// +kubebuilder:validation:Required
	RuleSetName *string `json:"ruleSetName"`
}

// ReceiptRuleSetStatus defines the observed state of ReceiptRuleSet
type ReceiptRuleSetStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// ReceiptRuleSet is the Schema for the ReceiptRuleSets API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type ReceiptRuleSet struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ReceiptRuleSetSpec   `json:"spec,omitempty"`
	Status            ReceiptRuleSetStatus `json:"status,omitempty"`
}

// ReceiptRuleSetList contains a list of ReceiptRuleSet
// +kubebuilder:object:root=true
type ReceiptRuleSetList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReceiptRuleSet `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ReceiptRuleSet{}, &ReceiptRuleSetList{})
}
