//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddHeaderAction) DeepCopyInto(out *AddHeaderAction) {
	*out = *in
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.HeaderValue != nil {
		in, out := &in.HeaderValue, &out.HeaderValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddHeaderAction.
func (in *AddHeaderAction) DeepCopy() *AddHeaderAction {
	if in == nil {
		return nil
	}
	out := new(AddHeaderAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BounceAction) DeepCopyInto(out *BounceAction) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Sender != nil {
		in, out := &in.Sender, &out.Sender
		*out = new(string)
		**out = **in
	}
	if in.SmtpReplyCode != nil {
		in, out := &in.SmtpReplyCode, &out.SmtpReplyCode
		*out = new(string)
		**out = **in
	}
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BounceAction.
func (in *BounceAction) DeepCopy() *BounceAction {
	if in == nil {
		return nil
	}
	out := new(BounceAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BouncedRecipientInfo) DeepCopyInto(out *BouncedRecipientInfo) {
	*out = *in
	if in.Recipient != nil {
		in, out := &in.Recipient, &out.Recipient
		*out = new(string)
		**out = **in
	}
	if in.RecipientARN != nil {
		in, out := &in.RecipientARN, &out.RecipientARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BouncedRecipientInfo.
func (in *BouncedRecipientInfo) DeepCopy() *BouncedRecipientInfo {
	if in == nil {
		return nil
	}
	out := new(BouncedRecipientInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchDestination) DeepCopyInto(out *CloudWatchDestination) {
	*out = *in
	if in.DimensionConfigurations != nil {
		in, out := &in.DimensionConfigurations, &out.DimensionConfigurations
		*out = make([]*CloudWatchDimensionConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CloudWatchDimensionConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchDestination.
func (in *CloudWatchDestination) DeepCopy() *CloudWatchDestination {
	if in == nil {
		return nil
	}
	out := new(CloudWatchDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchDimensionConfiguration) DeepCopyInto(out *CloudWatchDimensionConfiguration) {
	*out = *in
	if in.DefaultDimensionValue != nil {
		in, out := &in.DefaultDimensionValue, &out.DefaultDimensionValue
		*out = new(string)
		**out = **in
	}
	if in.DimensionName != nil {
		in, out := &in.DimensionName, &out.DimensionName
		*out = new(string)
		**out = **in
	}
	if in.DimensionValueSource != nil {
		in, out := &in.DimensionValueSource, &out.DimensionValueSource
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchDimensionConfiguration.
func (in *CloudWatchDimensionConfiguration) DeepCopy() *CloudWatchDimensionConfiguration {
	if in == nil {
		return nil
	}
	out := new(CloudWatchDimensionConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSet) DeepCopyInto(out *ConfigurationSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSet.
func (in *ConfigurationSet) DeepCopy() *ConfigurationSet {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigurationSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetEventDestination) DeepCopyInto(out *ConfigurationSetEventDestination) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetEventDestination.
func (in *ConfigurationSetEventDestination) DeepCopy() *ConfigurationSetEventDestination {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetEventDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigurationSetEventDestination) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetEventDestinationList) DeepCopyInto(out *ConfigurationSetEventDestinationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigurationSetEventDestination, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetEventDestinationList.
func (in *ConfigurationSetEventDestinationList) DeepCopy() *ConfigurationSetEventDestinationList {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetEventDestinationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigurationSetEventDestinationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetEventDestinationSpec) DeepCopyInto(out *ConfigurationSetEventDestinationSpec) {
	*out = *in
	if in.ConfigurationSetName != nil {
		in, out := &in.ConfigurationSetName, &out.ConfigurationSetName
		*out = new(string)
		**out = **in
	}
	if in.EventDestination != nil {
		in, out := &in.EventDestination, &out.EventDestination
		*out = new(EventDestination)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetEventDestinationSpec.
func (in *ConfigurationSetEventDestinationSpec) DeepCopy() *ConfigurationSetEventDestinationSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetEventDestinationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetEventDestinationStatus) DeepCopyInto(out *ConfigurationSetEventDestinationStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetEventDestinationStatus.
func (in *ConfigurationSetEventDestinationStatus) DeepCopy() *ConfigurationSetEventDestinationStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetEventDestinationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetList) DeepCopyInto(out *ConfigurationSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigurationSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetList.
func (in *ConfigurationSetList) DeepCopy() *ConfigurationSetList {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigurationSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetSpec) DeepCopyInto(out *ConfigurationSetSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetSpec.
func (in *ConfigurationSetSpec) DeepCopy() *ConfigurationSetSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSetStatus) DeepCopyInto(out *ConfigurationSetStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSetStatus.
func (in *ConfigurationSetStatus) DeepCopy() *ConfigurationSetStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSet_SDK) DeepCopyInto(out *ConfigurationSet_SDK) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSet_SDK.
func (in *ConfigurationSet_SDK) DeepCopy() *ConfigurationSet_SDK {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSet_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplate) DeepCopyInto(out *CustomVerificationEmailTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplate.
func (in *CustomVerificationEmailTemplate) DeepCopy() *CustomVerificationEmailTemplate {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomVerificationEmailTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateList) DeepCopyInto(out *CustomVerificationEmailTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomVerificationEmailTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateList.
func (in *CustomVerificationEmailTemplateList) DeepCopy() *CustomVerificationEmailTemplateList {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomVerificationEmailTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateSpec) DeepCopyInto(out *CustomVerificationEmailTemplateSpec) {
	*out = *in
	if in.FailureRedirectionURL != nil {
		in, out := &in.FailureRedirectionURL, &out.FailureRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.FromEmailAddress != nil {
		in, out := &in.FromEmailAddress, &out.FromEmailAddress
		*out = new(string)
		**out = **in
	}
	if in.SuccessRedirectionURL != nil {
		in, out := &in.SuccessRedirectionURL, &out.SuccessRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.TemplateContent != nil {
		in, out := &in.TemplateContent, &out.TemplateContent
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.TemplateSubject != nil {
		in, out := &in.TemplateSubject, &out.TemplateSubject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateSpec.
func (in *CustomVerificationEmailTemplateSpec) DeepCopy() *CustomVerificationEmailTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateStatus) DeepCopyInto(out *CustomVerificationEmailTemplateStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateStatus.
func (in *CustomVerificationEmailTemplateStatus) DeepCopy() *CustomVerificationEmailTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplate_SDK) DeepCopyInto(out *CustomVerificationEmailTemplate_SDK) {
	*out = *in
	if in.FailureRedirectionURL != nil {
		in, out := &in.FailureRedirectionURL, &out.FailureRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.FromEmailAddress != nil {
		in, out := &in.FromEmailAddress, &out.FromEmailAddress
		*out = new(string)
		**out = **in
	}
	if in.SuccessRedirectionURL != nil {
		in, out := &in.SuccessRedirectionURL, &out.SuccessRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.TemplateSubject != nil {
		in, out := &in.TemplateSubject, &out.TemplateSubject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplate_SDK.
func (in *CustomVerificationEmailTemplate_SDK) DeepCopy() *CustomVerificationEmailTemplate_SDK {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplate_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryOptions) DeepCopyInto(out *DeliveryOptions) {
	*out = *in
	if in.TLSPolicy != nil {
		in, out := &in.TLSPolicy, &out.TLSPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryOptions.
func (in *DeliveryOptions) DeepCopy() *DeliveryOptions {
	if in == nil {
		return nil
	}
	out := new(DeliveryOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventDestination) DeepCopyInto(out *EventDestination) {
	*out = *in
	if in.CloudWatchDestination != nil {
		in, out := &in.CloudWatchDestination, &out.CloudWatchDestination
		*out = new(CloudWatchDestination)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.KinesisFirehoseDestination != nil {
		in, out := &in.KinesisFirehoseDestination, &out.KinesisFirehoseDestination
		*out = new(KinesisFirehoseDestination)
		(*in).DeepCopyInto(*out)
	}
	if in.MatchingEventTypes != nil {
		in, out := &in.MatchingEventTypes, &out.MatchingEventTypes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SNSDestination != nil {
		in, out := &in.SNSDestination, &out.SNSDestination
		*out = new(SNSDestination)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventDestination.
func (in *EventDestination) DeepCopy() *EventDestination {
	if in == nil {
		return nil
	}
	out := new(EventDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDkimAttributes) DeepCopyInto(out *IdentityDkimAttributes) {
	*out = *in
	if in.DkimEnabled != nil {
		in, out := &in.DkimEnabled, &out.DkimEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDkimAttributes.
func (in *IdentityDkimAttributes) DeepCopy() *IdentityDkimAttributes {
	if in == nil {
		return nil
	}
	out := new(IdentityDkimAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityNotificationAttributes) DeepCopyInto(out *IdentityNotificationAttributes) {
	*out = *in
	if in.ForwardingEnabled != nil {
		in, out := &in.ForwardingEnabled, &out.ForwardingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInBounceNotificationsEnabled != nil {
		in, out := &in.HeadersInBounceNotificationsEnabled, &out.HeadersInBounceNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInComplaintNotificationsEnabled != nil {
		in, out := &in.HeadersInComplaintNotificationsEnabled, &out.HeadersInComplaintNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInDeliveryNotificationsEnabled != nil {
		in, out := &in.HeadersInDeliveryNotificationsEnabled, &out.HeadersInDeliveryNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityNotificationAttributes.
func (in *IdentityNotificationAttributes) DeepCopy() *IdentityNotificationAttributes {
	if in == nil {
		return nil
	}
	out := new(IdentityNotificationAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KinesisFirehoseDestination) DeepCopyInto(out *KinesisFirehoseDestination) {
	*out = *in
	if in.DeliveryStreamARN != nil {
		in, out := &in.DeliveryStreamARN, &out.DeliveryStreamARN
		*out = new(string)
		**out = **in
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KinesisFirehoseDestination.
func (in *KinesisFirehoseDestination) DeepCopy() *KinesisFirehoseDestination {
	if in == nil {
		return nil
	}
	out := new(KinesisFirehoseDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaAction) DeepCopyInto(out *LambdaAction) {
	*out = *in
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.InvocationType != nil {
		in, out := &in.InvocationType, &out.InvocationType
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaAction.
func (in *LambdaAction) DeepCopy() *LambdaAction {
	if in == nil {
		return nil
	}
	out := new(LambdaAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptAction) DeepCopyInto(out *ReceiptAction) {
	*out = *in
	if in.AddHeaderAction != nil {
		in, out := &in.AddHeaderAction, &out.AddHeaderAction
		*out = new(AddHeaderAction)
		(*in).DeepCopyInto(*out)
	}
	if in.BounceAction != nil {
		in, out := &in.BounceAction, &out.BounceAction
		*out = new(BounceAction)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaAction != nil {
		in, out := &in.LambdaAction, &out.LambdaAction
		*out = new(LambdaAction)
		(*in).DeepCopyInto(*out)
	}
	if in.S3Action != nil {
		in, out := &in.S3Action, &out.S3Action
		*out = new(S3Action)
		(*in).DeepCopyInto(*out)
	}
	if in.SNSAction != nil {
		in, out := &in.SNSAction, &out.SNSAction
		*out = new(SNSAction)
		(*in).DeepCopyInto(*out)
	}
	if in.StopAction != nil {
		in, out := &in.StopAction, &out.StopAction
		*out = new(StopAction)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkmailAction != nil {
		in, out := &in.WorkmailAction, &out.WorkmailAction
		*out = new(WorkmailAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptAction.
func (in *ReceiptAction) DeepCopy() *ReceiptAction {
	if in == nil {
		return nil
	}
	out := new(ReceiptAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptFilter) DeepCopyInto(out *ReceiptFilter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptFilter.
func (in *ReceiptFilter) DeepCopy() *ReceiptFilter {
	if in == nil {
		return nil
	}
	out := new(ReceiptFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReceiptFilter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptFilterList) DeepCopyInto(out *ReceiptFilterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReceiptFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptFilterList.
func (in *ReceiptFilterList) DeepCopy() *ReceiptFilterList {
	if in == nil {
		return nil
	}
	out := new(ReceiptFilterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReceiptFilterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptFilterSpec) DeepCopyInto(out *ReceiptFilterSpec) {
	*out = *in
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(ReceiptFilter_SDK)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptFilterSpec.
func (in *ReceiptFilterSpec) DeepCopy() *ReceiptFilterSpec {
	if in == nil {
		return nil
	}
	out := new(ReceiptFilterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptFilterStatus) DeepCopyInto(out *ReceiptFilterStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptFilterStatus.
func (in *ReceiptFilterStatus) DeepCopy() *ReceiptFilterStatus {
	if in == nil {
		return nil
	}
	out := new(ReceiptFilterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptFilter_SDK) DeepCopyInto(out *ReceiptFilter_SDK) {
	*out = *in
	if in.IPFilter != nil {
		in, out := &in.IPFilter, &out.IPFilter
		*out = new(ReceiptIPFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptFilter_SDK.
func (in *ReceiptFilter_SDK) DeepCopy() *ReceiptFilter_SDK {
	if in == nil {
		return nil
	}
	out := new(ReceiptFilter_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptIPFilter) DeepCopyInto(out *ReceiptIPFilter) {
	*out = *in
	if in.CIDR != nil {
		in, out := &in.CIDR, &out.CIDR
		*out = new(string)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptIPFilter.
func (in *ReceiptIPFilter) DeepCopy() *ReceiptIPFilter {
	if in == nil {
		return nil
	}
	out := new(ReceiptIPFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRule) DeepCopyInto(out *ReceiptRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRule.
func (in *ReceiptRule) DeepCopy() *ReceiptRule {
	if in == nil {
		return nil
	}
	out := new(ReceiptRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReceiptRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleList) DeepCopyInto(out *ReceiptRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReceiptRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleList.
func (in *ReceiptRuleList) DeepCopy() *ReceiptRuleList {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReceiptRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSet) DeepCopyInto(out *ReceiptRuleSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSet.
func (in *ReceiptRuleSet) DeepCopy() *ReceiptRuleSet {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReceiptRuleSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSetList) DeepCopyInto(out *ReceiptRuleSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReceiptRuleSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSetList.
func (in *ReceiptRuleSetList) DeepCopy() *ReceiptRuleSetList {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReceiptRuleSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSetMetadata) DeepCopyInto(out *ReceiptRuleSetMetadata) {
	*out = *in
	if in.CreatedTimestamp != nil {
		in, out := &in.CreatedTimestamp, &out.CreatedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSetMetadata.
func (in *ReceiptRuleSetMetadata) DeepCopy() *ReceiptRuleSetMetadata {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSetMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSetSpec) DeepCopyInto(out *ReceiptRuleSetSpec) {
	*out = *in
	if in.RuleSetName != nil {
		in, out := &in.RuleSetName, &out.RuleSetName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSetSpec.
func (in *ReceiptRuleSetSpec) DeepCopy() *ReceiptRuleSetSpec {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSetStatus) DeepCopyInto(out *ReceiptRuleSetStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSetStatus.
func (in *ReceiptRuleSetStatus) DeepCopy() *ReceiptRuleSetStatus {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSpec) DeepCopyInto(out *ReceiptRuleSpec) {
	*out = *in
	if in.After != nil {
		in, out := &in.After, &out.After
		*out = new(string)
		**out = **in
	}
	if in.Rule != nil {
		in, out := &in.Rule, &out.Rule
		*out = new(ReceiptRule_SDK)
		(*in).DeepCopyInto(*out)
	}
	if in.RuleSetName != nil {
		in, out := &in.RuleSetName, &out.RuleSetName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSpec.
func (in *ReceiptRuleSpec) DeepCopy() *ReceiptRuleSpec {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleStatus) DeepCopyInto(out *ReceiptRuleStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleStatus.
func (in *ReceiptRuleStatus) DeepCopy() *ReceiptRuleStatus {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRule_SDK) DeepCopyInto(out *ReceiptRule_SDK) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]*ReceiptAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ReceiptAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScanEnabled != nil {
		in, out := &in.ScanEnabled, &out.ScanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TLSPolicy != nil {
		in, out := &in.TLSPolicy, &out.TLSPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRule_SDK.
func (in *ReceiptRule_SDK) DeepCopy() *ReceiptRule_SDK {
	if in == nil {
		return nil
	}
	out := new(ReceiptRule_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecipientDsnFields) DeepCopyInto(out *RecipientDsnFields) {
	*out = *in
	if in.FinalRecipient != nil {
		in, out := &in.FinalRecipient, &out.FinalRecipient
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecipientDsnFields.
func (in *RecipientDsnFields) DeepCopy() *RecipientDsnFields {
	if in == nil {
		return nil
	}
	out := new(RecipientDsnFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReputationOptions) DeepCopyInto(out *ReputationOptions) {
	*out = *in
	if in.LastFreshStart != nil {
		in, out := &in.LastFreshStart, &out.LastFreshStart
		*out = (*in).DeepCopy()
	}
	if in.ReputationMetricsEnabled != nil {
		in, out := &in.ReputationMetricsEnabled, &out.ReputationMetricsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendingEnabled != nil {
		in, out := &in.SendingEnabled, &out.SendingEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReputationOptions.
func (in *ReputationOptions) DeepCopy() *ReputationOptions {
	if in == nil {
		return nil
	}
	out := new(ReputationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Action) DeepCopyInto(out *S3Action) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyARN != nil {
		in, out := &in.KMSKeyARN, &out.KMSKeyARN
		*out = new(string)
		**out = **in
	}
	if in.ObjectKeyPrefix != nil {
		in, out := &in.ObjectKeyPrefix, &out.ObjectKeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Action.
func (in *S3Action) DeepCopy() *S3Action {
	if in == nil {
		return nil
	}
	out := new(S3Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSAction) DeepCopyInto(out *SNSAction) {
	*out = *in
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSAction.
func (in *SNSAction) DeepCopy() *SNSAction {
	if in == nil {
		return nil
	}
	out := new(SNSAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSDestination) DeepCopyInto(out *SNSDestination) {
	*out = *in
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
	if in.TopicRef != nil {
		in, out := &in.TopicRef, &out.TopicRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSDestination.
func (in *SNSDestination) DeepCopy() *SNSDestination {
	if in == nil {
		return nil
	}
	out := new(SNSDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SendDataPoint) DeepCopyInto(out *SendDataPoint) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SendDataPoint.
func (in *SendDataPoint) DeepCopy() *SendDataPoint {
	if in == nil {
		return nil
	}
	out := new(SendDataPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopAction) DeepCopyInto(out *StopAction) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopAction.
func (in *StopAction) DeepCopy() *StopAction {
	if in == nil {
		return nil
	}
	out := new(StopAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Template) DeepCopyInto(out *Template) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Template.
func (in *Template) DeepCopy() *Template {
	if in == nil {
		return nil
	}
	out := new(Template)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Template) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateList) DeepCopyInto(out *TemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Template, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateList.
func (in *TemplateList) DeepCopy() *TemplateList {
	if in == nil {
		return nil
	}
	out := new(TemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateMetadata) DeepCopyInto(out *TemplateMetadata) {
	*out = *in
	if in.CreatedTimestamp != nil {
		in, out := &in.CreatedTimestamp, &out.CreatedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateMetadata.
func (in *TemplateMetadata) DeepCopy() *TemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(TemplateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateSpec) DeepCopyInto(out *TemplateSpec) {
	*out = *in
	if in.HTMLPart != nil {
		in, out := &in.HTMLPart, &out.HTMLPart
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SubjectPart != nil {
		in, out := &in.SubjectPart, &out.SubjectPart
		*out = new(string)
		**out = **in
	}
	if in.TextPart != nil {
		in, out := &in.TextPart, &out.TextPart
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateSpec.
func (in *TemplateSpec) DeepCopy() *TemplateSpec {
	if in == nil {
		return nil
	}
	out := new(TemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateStatus) DeepCopyInto(out *TemplateStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateStatus.
func (in *TemplateStatus) DeepCopy() *TemplateStatus {
	if in == nil {
		return nil
	}
	out := new(TemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Template_SDK) DeepCopyInto(out *Template_SDK) {
	*out = *in
	if in.HTMLPart != nil {
		in, out := &in.HTMLPart, &out.HTMLPart
		*out = new(string)
		**out = **in
	}
	if in.SubjectPart != nil {
		in, out := &in.SubjectPart, &out.SubjectPart
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.TextPart != nil {
		in, out := &in.TextPart, &out.TextPart
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Template_SDK.
func (in *Template_SDK) DeepCopy() *Template_SDK {
	if in == nil {
		return nil
	}
	out := new(Template_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackingOptions) DeepCopyInto(out *TrackingOptions) {
	*out = *in
	if in.CustomRedirectDomain != nil {
		in, out := &in.CustomRedirectDomain, &out.CustomRedirectDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackingOptions.
func (in *TrackingOptions) DeepCopy() *TrackingOptions {
	if in == nil {
		return nil
	}
	out := new(TrackingOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkmailAction) DeepCopyInto(out *WorkmailAction) {
	*out = *in
	if in.OrganizationARN != nil {
		in, out := &in.OrganizationARN, &out.OrganizationARN
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkmailAction.
func (in *WorkmailAction) DeepCopy() *WorkmailAction {
	if in == nil {
		return nil
	}
	out := new(WorkmailAction)
	in.DeepCopyInto(out)
	return out
}
