//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplate) DeepCopyInto(out *CustomVerificationEmailTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplate.
func (in *CustomVerificationEmailTemplate) DeepCopy() *CustomVerificationEmailTemplate {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomVerificationEmailTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateList) DeepCopyInto(out *CustomVerificationEmailTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomVerificationEmailTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateList.
func (in *CustomVerificationEmailTemplateList) DeepCopy() *CustomVerificationEmailTemplateList {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomVerificationEmailTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateSpec) DeepCopyInto(out *CustomVerificationEmailTemplateSpec) {
	*out = *in
	if in.FailureRedirectionURL != nil {
		in, out := &in.FailureRedirectionURL, &out.FailureRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.FromEmailAddress != nil {
		in, out := &in.FromEmailAddress, &out.FromEmailAddress
		*out = new(string)
		**out = **in
	}
	if in.SuccessRedirectionURL != nil {
		in, out := &in.SuccessRedirectionURL, &out.SuccessRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.TemplateContent != nil {
		in, out := &in.TemplateContent, &out.TemplateContent
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.TemplateSubject != nil {
		in, out := &in.TemplateSubject, &out.TemplateSubject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateSpec.
func (in *CustomVerificationEmailTemplateSpec) DeepCopy() *CustomVerificationEmailTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateStatus) DeepCopyInto(out *CustomVerificationEmailTemplateStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateStatus.
func (in *CustomVerificationEmailTemplateStatus) DeepCopy() *CustomVerificationEmailTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplate_SDK) DeepCopyInto(out *CustomVerificationEmailTemplate_SDK) {
	*out = *in
	if in.FailureRedirectionURL != nil {
		in, out := &in.FailureRedirectionURL, &out.FailureRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.FromEmailAddress != nil {
		in, out := &in.FromEmailAddress, &out.FromEmailAddress
		*out = new(string)
		**out = **in
	}
	if in.SuccessRedirectionURL != nil {
		in, out := &in.SuccessRedirectionURL, &out.SuccessRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.TemplateSubject != nil {
		in, out := &in.TemplateSubject, &out.TemplateSubject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplate_SDK.
func (in *CustomVerificationEmailTemplate_SDK) DeepCopy() *CustomVerificationEmailTemplate_SDK {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplate_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Template) DeepCopyInto(out *Template) {
	*out = *in
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Template.
func (in *Template) DeepCopy() *Template {
	if in == nil {
		return nil
	}
	out := new(Template)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateMetadata) DeepCopyInto(out *TemplateMetadata) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateMetadata.
func (in *TemplateMetadata) DeepCopy() *TemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(TemplateMetadata)
	in.DeepCopyInto(out)
	return out
}
