//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddHeaderAction) DeepCopyInto(out *AddHeaderAction) {
	*out = *in
	if in.HeaderName != nil {
		in, out := &in.HeaderName, &out.HeaderName
		*out = new(string)
		**out = **in
	}
	if in.HeaderValue != nil {
		in, out := &in.HeaderValue, &out.HeaderValue
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddHeaderAction.
func (in *AddHeaderAction) DeepCopy() *AddHeaderAction {
	if in == nil {
		return nil
	}
	out := new(AddHeaderAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BounceAction) DeepCopyInto(out *BounceAction) {
	*out = *in
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Sender != nil {
		in, out := &in.Sender, &out.Sender
		*out = new(string)
		**out = **in
	}
	if in.SmtpReplyCode != nil {
		in, out := &in.SmtpReplyCode, &out.SmtpReplyCode
		*out = new(string)
		**out = **in
	}
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BounceAction.
func (in *BounceAction) DeepCopy() *BounceAction {
	if in == nil {
		return nil
	}
	out := new(BounceAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BouncedRecipientInfo) DeepCopyInto(out *BouncedRecipientInfo) {
	*out = *in
	if in.Recipient != nil {
		in, out := &in.Recipient, &out.Recipient
		*out = new(string)
		**out = **in
	}
	if in.RecipientARN != nil {
		in, out := &in.RecipientARN, &out.RecipientARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BouncedRecipientInfo.
func (in *BouncedRecipientInfo) DeepCopy() *BouncedRecipientInfo {
	if in == nil {
		return nil
	}
	out := new(BouncedRecipientInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplate) DeepCopyInto(out *CustomVerificationEmailTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplate.
func (in *CustomVerificationEmailTemplate) DeepCopy() *CustomVerificationEmailTemplate {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomVerificationEmailTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateList) DeepCopyInto(out *CustomVerificationEmailTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomVerificationEmailTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateList.
func (in *CustomVerificationEmailTemplateList) DeepCopy() *CustomVerificationEmailTemplateList {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomVerificationEmailTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateSpec) DeepCopyInto(out *CustomVerificationEmailTemplateSpec) {
	*out = *in
	if in.FailureRedirectionURL != nil {
		in, out := &in.FailureRedirectionURL, &out.FailureRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.FromEmailAddress != nil {
		in, out := &in.FromEmailAddress, &out.FromEmailAddress
		*out = new(string)
		**out = **in
	}
	if in.SuccessRedirectionURL != nil {
		in, out := &in.SuccessRedirectionURL, &out.SuccessRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.TemplateContent != nil {
		in, out := &in.TemplateContent, &out.TemplateContent
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.TemplateSubject != nil {
		in, out := &in.TemplateSubject, &out.TemplateSubject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateSpec.
func (in *CustomVerificationEmailTemplateSpec) DeepCopy() *CustomVerificationEmailTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplateStatus) DeepCopyInto(out *CustomVerificationEmailTemplateStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplateStatus.
func (in *CustomVerificationEmailTemplateStatus) DeepCopy() *CustomVerificationEmailTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomVerificationEmailTemplate_SDK) DeepCopyInto(out *CustomVerificationEmailTemplate_SDK) {
	*out = *in
	if in.FailureRedirectionURL != nil {
		in, out := &in.FailureRedirectionURL, &out.FailureRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.FromEmailAddress != nil {
		in, out := &in.FromEmailAddress, &out.FromEmailAddress
		*out = new(string)
		**out = **in
	}
	if in.SuccessRedirectionURL != nil {
		in, out := &in.SuccessRedirectionURL, &out.SuccessRedirectionURL
		*out = new(string)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
	if in.TemplateSubject != nil {
		in, out := &in.TemplateSubject, &out.TemplateSubject
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomVerificationEmailTemplate_SDK.
func (in *CustomVerificationEmailTemplate_SDK) DeepCopy() *CustomVerificationEmailTemplate_SDK {
	if in == nil {
		return nil
	}
	out := new(CustomVerificationEmailTemplate_SDK)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryOptions) DeepCopyInto(out *DeliveryOptions) {
	*out = *in
	if in.TLSPolicy != nil {
		in, out := &in.TLSPolicy, &out.TLSPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryOptions.
func (in *DeliveryOptions) DeepCopy() *DeliveryOptions {
	if in == nil {
		return nil
	}
	out := new(DeliveryOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventDestination) DeepCopyInto(out *EventDestination) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventDestination.
func (in *EventDestination) DeepCopy() *EventDestination {
	if in == nil {
		return nil
	}
	out := new(EventDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityDkimAttributes) DeepCopyInto(out *IdentityDkimAttributes) {
	*out = *in
	if in.DkimEnabled != nil {
		in, out := &in.DkimEnabled, &out.DkimEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityDkimAttributes.
func (in *IdentityDkimAttributes) DeepCopy() *IdentityDkimAttributes {
	if in == nil {
		return nil
	}
	out := new(IdentityDkimAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityNotificationAttributes) DeepCopyInto(out *IdentityNotificationAttributes) {
	*out = *in
	if in.ForwardingEnabled != nil {
		in, out := &in.ForwardingEnabled, &out.ForwardingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInBounceNotificationsEnabled != nil {
		in, out := &in.HeadersInBounceNotificationsEnabled, &out.HeadersInBounceNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInComplaintNotificationsEnabled != nil {
		in, out := &in.HeadersInComplaintNotificationsEnabled, &out.HeadersInComplaintNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.HeadersInDeliveryNotificationsEnabled != nil {
		in, out := &in.HeadersInDeliveryNotificationsEnabled, &out.HeadersInDeliveryNotificationsEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityNotificationAttributes.
func (in *IdentityNotificationAttributes) DeepCopy() *IdentityNotificationAttributes {
	if in == nil {
		return nil
	}
	out := new(IdentityNotificationAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KinesisFirehoseDestination) DeepCopyInto(out *KinesisFirehoseDestination) {
	*out = *in
	if in.DeliveryStreamARN != nil {
		in, out := &in.DeliveryStreamARN, &out.DeliveryStreamARN
		*out = new(string)
		**out = **in
	}
	if in.IAMRoleARN != nil {
		in, out := &in.IAMRoleARN, &out.IAMRoleARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KinesisFirehoseDestination.
func (in *KinesisFirehoseDestination) DeepCopy() *KinesisFirehoseDestination {
	if in == nil {
		return nil
	}
	out := new(KinesisFirehoseDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LambdaAction) DeepCopyInto(out *LambdaAction) {
	*out = *in
	if in.FunctionARN != nil {
		in, out := &in.FunctionARN, &out.FunctionARN
		*out = new(string)
		**out = **in
	}
	if in.InvocationType != nil {
		in, out := &in.InvocationType, &out.InvocationType
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LambdaAction.
func (in *LambdaAction) DeepCopy() *LambdaAction {
	if in == nil {
		return nil
	}
	out := new(LambdaAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptAction) DeepCopyInto(out *ReceiptAction) {
	*out = *in
	if in.AddHeaderAction != nil {
		in, out := &in.AddHeaderAction, &out.AddHeaderAction
		*out = new(AddHeaderAction)
		(*in).DeepCopyInto(*out)
	}
	if in.BounceAction != nil {
		in, out := &in.BounceAction, &out.BounceAction
		*out = new(BounceAction)
		(*in).DeepCopyInto(*out)
	}
	if in.LambdaAction != nil {
		in, out := &in.LambdaAction, &out.LambdaAction
		*out = new(LambdaAction)
		(*in).DeepCopyInto(*out)
	}
	if in.S3Action != nil {
		in, out := &in.S3Action, &out.S3Action
		*out = new(S3Action)
		(*in).DeepCopyInto(*out)
	}
	if in.SNSAction != nil {
		in, out := &in.SNSAction, &out.SNSAction
		*out = new(SNSAction)
		(*in).DeepCopyInto(*out)
	}
	if in.StopAction != nil {
		in, out := &in.StopAction, &out.StopAction
		*out = new(StopAction)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkmailAction != nil {
		in, out := &in.WorkmailAction, &out.WorkmailAction
		*out = new(WorkmailAction)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptAction.
func (in *ReceiptAction) DeepCopy() *ReceiptAction {
	if in == nil {
		return nil
	}
	out := new(ReceiptAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRule) DeepCopyInto(out *ReceiptRule) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]*ReceiptAction, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ReceiptAction)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScanEnabled != nil {
		in, out := &in.ScanEnabled, &out.ScanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TLSPolicy != nil {
		in, out := &in.TLSPolicy, &out.TLSPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRule.
func (in *ReceiptRule) DeepCopy() *ReceiptRule {
	if in == nil {
		return nil
	}
	out := new(ReceiptRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSet) DeepCopyInto(out *ReceiptRuleSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSet.
func (in *ReceiptRuleSet) DeepCopy() *ReceiptRuleSet {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReceiptRuleSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSetList) DeepCopyInto(out *ReceiptRuleSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ReceiptRuleSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSetList.
func (in *ReceiptRuleSetList) DeepCopy() *ReceiptRuleSetList {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ReceiptRuleSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSetMetadata) DeepCopyInto(out *ReceiptRuleSetMetadata) {
	*out = *in
	if in.CreatedTimestamp != nil {
		in, out := &in.CreatedTimestamp, &out.CreatedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSetMetadata.
func (in *ReceiptRuleSetMetadata) DeepCopy() *ReceiptRuleSetMetadata {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSetMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSetSpec) DeepCopyInto(out *ReceiptRuleSetSpec) {
	*out = *in
	if in.RuleSetName != nil {
		in, out := &in.RuleSetName, &out.RuleSetName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSetSpec.
func (in *ReceiptRuleSetSpec) DeepCopy() *ReceiptRuleSetSpec {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReceiptRuleSetStatus) DeepCopyInto(out *ReceiptRuleSetStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReceiptRuleSetStatus.
func (in *ReceiptRuleSetStatus) DeepCopy() *ReceiptRuleSetStatus {
	if in == nil {
		return nil
	}
	out := new(ReceiptRuleSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecipientDsnFields) DeepCopyInto(out *RecipientDsnFields) {
	*out = *in
	if in.FinalRecipient != nil {
		in, out := &in.FinalRecipient, &out.FinalRecipient
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecipientDsnFields.
func (in *RecipientDsnFields) DeepCopy() *RecipientDsnFields {
	if in == nil {
		return nil
	}
	out := new(RecipientDsnFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReputationOptions) DeepCopyInto(out *ReputationOptions) {
	*out = *in
	if in.ReputationMetricsEnabled != nil {
		in, out := &in.ReputationMetricsEnabled, &out.ReputationMetricsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.SendingEnabled != nil {
		in, out := &in.SendingEnabled, &out.SendingEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReputationOptions.
func (in *ReputationOptions) DeepCopy() *ReputationOptions {
	if in == nil {
		return nil
	}
	out := new(ReputationOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Action) DeepCopyInto(out *S3Action) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyARN != nil {
		in, out := &in.KMSKeyARN, &out.KMSKeyARN
		*out = new(string)
		**out = **in
	}
	if in.ObjectKeyPrefix != nil {
		in, out := &in.ObjectKeyPrefix, &out.ObjectKeyPrefix
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Action.
func (in *S3Action) DeepCopy() *S3Action {
	if in == nil {
		return nil
	}
	out := new(S3Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSAction) DeepCopyInto(out *SNSAction) {
	*out = *in
	if in.Encoding != nil {
		in, out := &in.Encoding, &out.Encoding
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSAction.
func (in *SNSAction) DeepCopy() *SNSAction {
	if in == nil {
		return nil
	}
	out := new(SNSAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SNSDestination) DeepCopyInto(out *SNSDestination) {
	*out = *in
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SNSDestination.
func (in *SNSDestination) DeepCopy() *SNSDestination {
	if in == nil {
		return nil
	}
	out := new(SNSDestination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SendDataPoint) DeepCopyInto(out *SendDataPoint) {
	*out = *in
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SendDataPoint.
func (in *SendDataPoint) DeepCopy() *SendDataPoint {
	if in == nil {
		return nil
	}
	out := new(SendDataPoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StopAction) DeepCopyInto(out *StopAction) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StopAction.
func (in *StopAction) DeepCopy() *StopAction {
	if in == nil {
		return nil
	}
	out := new(StopAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Template) DeepCopyInto(out *Template) {
	*out = *in
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Template.
func (in *Template) DeepCopy() *Template {
	if in == nil {
		return nil
	}
	out := new(Template)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateMetadata) DeepCopyInto(out *TemplateMetadata) {
	*out = *in
	if in.CreatedTimestamp != nil {
		in, out := &in.CreatedTimestamp, &out.CreatedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateMetadata.
func (in *TemplateMetadata) DeepCopy() *TemplateMetadata {
	if in == nil {
		return nil
	}
	out := new(TemplateMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkmailAction) DeepCopyInto(out *WorkmailAction) {
	*out = *in
	if in.OrganizationARN != nil {
		in, out := &in.OrganizationARN, &out.OrganizationARN
		*out = new(string)
		**out = **in
	}
	if in.TopicARN != nil {
		in, out := &in.TopicARN, &out.TopicARN
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkmailAction.
func (in *WorkmailAction) DeepCopy() *WorkmailAction {
	if in == nil {
		return nil
	}
	out := new(WorkmailAction)
	in.DeepCopyInto(out)
	return out
}
